### ISSUE TITLE
Cannot import csrc from gsplat

### ISSUE THREAD

**Issue by TianshuangQiu** [nerfstudio-project/gsplat#311]
I am currently using python3.8, CUDA12.1. All python imports can load without error, but when I call the `reasterization` function, the error below happens. The last time this was an issue, the solution was to build from 0.3.0. Is that still the recommended fix?

```
Traceback (most recent call last):
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/cuda/_backend.py", line 46, in <module>
    from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/curobot/dev_lib/MonoGS/utils/slam_backend.py", line 408, in run
    self.initialize_map(cur_frame_idx, viewpoint)
  File "/home/curobot/dev_lib/MonoGS/utils/slam_backend.py", line 89, in initialize_map
    render_pkg = render(
  File "/home/curobot/dev_lib/MonoGS/gaussian_splatting/gaussian_renderer/__init__.py", line 119, in render
    gsplat_out = rasterization(
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/rendering.py", line 218, in rasterization
    proj_results = fully_fused_projection(
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/cuda/_wrapper.py", line 243, in fully_fused_projection
    return _FullyFusedProjectionPacked.apply(
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/cuda/_wrapper.py", line 972, in forward
    ) = _make_lazy_cuda_func("fully_fused_projection_packed_fwd")(
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/cuda/_wrapper.py", line 10, in call_cuda
    from ._backend import _C
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/gsplat/cuda/_backend.py", line 92, in <module>
    _C = load(
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1747, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/curobot/miniconda3/envs/bonogs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2141, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/curobot/.cache/torch_extensions/py38_cu121/gsplat_cuda/gsplat_cuda.so: cannot open shared object file: No such file or directory


```

**Comment by thesantatitan** [comment]
@TianshuangQiu  did you end up solving it?

**Comment by Atticuszz** [comment]
#280 same issue here bro，

**Comment by thesantatitan** [comment]
Switching to v3.1.1 fixed this for me

**Comment by TianshuangQiu** [comment]
I did indeed fix it! It required me to install the proper version of cuda toolkit from conda
`conda install -c "nvidia/label/cuda-11.6.0" cuda-toolkit`

**Comment by liyaowei-stu** [comment]
Same issue. My cuda is 12.1, torch is 2.2.0.

**Comment by lionlai1989** [comment]
i faced the same error. The overall solution for me is to use `cuda-11.8`. after numerous experiments, i found that `nerfstudio`, `tiny-cuda-nn` and `gsplat` only work perfectly on `cuda-11.8`.

**Comment by RayYoh** [comment]
With cuda-11.7, I solve this problem by updating the torch from 1.13.0 to 1.13.1.

**Comment by jimy-byerley** [comment]
I had the same issue and solved it like linked above
But it seems to me that this import error `ImportError: cannot import name 'csrc' from 'gsplat'` is triggered when the compiler did not run, which is not explicit at all in this message and no detail is given about the reason the compiler did not work.

I suggest forwarding the compiler errors and changing this error message.

**Comment by Watson-OU-221** [comment]
> i faced the same error. The overall solution for me is to use `cuda-11.8`. after numerous experiments, i found that `nerfstudio`, `tiny-cuda-nn` and `gsplat` only work perfectly on `cuda-11.8`.

I met this problem that confused me a lot. After I create a new conda environment with: 

1. pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118

2. conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit

Then, installed the dependancies according to the examples/requirements.txt, I finally solved it. OMG~
