### PR TITLE
Fixes build issues but only works with pytorch >= 2.2

### PR DESCRIPTION
**Pull request by MrNeRF**
As described here: https://github.com/nerfstudio-project/gsplat/pull/583
the pr 583 introduced some build issues. It also still does not work with pytorch < 2.2

I leave it here as a first commit to get the issues fixed.

### CODE REVIEW

**Comment by liruilong940607** [comment]
btw i removed environment.yml in a followed up PR. As it contains many unnecessary dependencies for the gsplat library itself, while contains insufficient dependencies for the code under examples/. Hope this makes sense!

**Comment by MrNeRF** [comment]
Nice, thank you! I will test it later on.

**Comment by joel-evercoast** [comment]
For anyone else dealing with sudden failed builds from the git repo, whether from main or from tagged releases, the fix for me was to pin `setuptools==69.5.1`.

Newer versions of setuptools caused a variety of failures, either at build time:

`TypeError: Command.__init__() got an unexpected keyword argument 'no_python_abi_suffix'`

or afterwards getting an error about a missing `gsplat_cuda.so` file in the pytorch cache.
